[package]
name = "bitcoin-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bnum = { version = "0.11.0", features = ["nightly"] }
sha2 = "0.10.8"
digest = "0.10.7"
hmac = "0.12.1"
