[package]
name = "bitcoin-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bnum = { version = "0.13.0", features = ["nightly"] }
sha2 = "0.10.8"
hmac = "0.12.1"
once_cell = "1.19.0"
ripemd = "0.1.3"

[dev-dependencies]
rand = "0.9.0"
